version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  kafka-message:
    lang: go
    handler: ./kafka-message
    image: hbouvier/function-simple-kafka-message:latest
    secrets:
    - function-simple-kafka-consumer
    readonly_root_filesystem: true
    annotations:
      topic: request
    environment:
      response_topic: response

